"""Automated Markdown report generator module."""

import os
from typing import Dict, Any


class ReportGenerator:
    """Generates structured Markdown analysis reports."""

    def __init__(self, output_path: str = "report/REPORT_CONTENT.md"):
        self.output_path = output_path

    def build_report(self, results: Dict[str, Any]) -> str:
        """Construct report string from evaluation dictionary."""
        metrics = results.get("metrics", {})
        objects = results.get("objects", [])
        faces = results.get("faces", [])

        report_md = f"""# Automated Computer Vision Analysis Report

**Status:** Completed  

---

## Executive Summary
This automated report summarizes the findings from the computer vision analysis pipeline executed on input datasets.

## Image Analysis Metrics
- **Dimensions:** {metrics.get('width', 'N/A')} x {metrics.get('height', 'N/A')} (Channels: {metrics.get('channels', 'N/A')})
- **Mean Brightness:** {metrics.get('mean_brightness', 'N/A')} / 255
- **Contrast (Std Dev):** {metrics.get('std_contrast', 'N/A')}

## Object Detection
- **Total Objects Detected:** {len(objects)}
"""
        for i, obj in enumerate(objects, 1):
            report_md += f"  - Object {i}: Label='{obj.get('label')}', Confidence={obj.get('confidence')}
"

        report_md += f"""
## Face Detection
- **Total Faces Detected:** {len(faces)}
"""
        for i, face in enumerate(faces, 1):
            report_md += f"  - Face {i}: Confidence={face.get('confidence')}, BBox={face.get('bbox')}
"

        report_md += """
---
*Report automatically generated by `modules/report_generator.py`.*
"""
        return report_md

    def save_report(self, results: Dict[str, Any]) -> str:
        """Generate and save report to disk."""
        content = self.build_report(results)
        os.makedirs(os.path.dirname(self.output_path), exist_ok=True)
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return self.output_path
